# Generated by Django 5.0.4 on 2024-05-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.FloatField(choices=[(1.0, '1 star'), (1.5, '1.5 stars'), (2.0, '2 stars'), (2.5, '2.5 stars'), (3.0, '3 stars'), (3.5, '3.5 stars'), (4.0, '4 stars'), (4.5, '4.5 stars'), (5.0, '5 stars')], null=True),
        ),
    ]
