# Generated by Django 5.0.4 on 2024-05-19 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_remove_movie_genre_movie_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='director',
        ),
    ]
