# Generated by Django 5.0.4 on 2024-10-08 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_movie_backdrop_path_movie_credit_movie_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='youtube_path',
            field=models.URLField(blank=True, null=True),
        ),
    ]
